const { Markup } = require('telegraf')
const bot = require("./token")
const { start, datE } = require("./keyborad")
const { tell_people, Z } = require("./horatxkon")
console.log("++++++++++")
bot.start(ctx => ctx.reply(`Привет, ${ctx.message.from.first_name}`, datE()))
bot.hears("DATE", ctx => ctx.reply(new Date(), start()))
bot.hears(Z, ctx => ctx.reply(tell_people(ctx.message.text)))
bot.hears("Назад", ctx => ctx.reply("OK!", datE()))